### ISSUE TITLE
提示语中的单词拼写错误 😂

### ISSUE THREAD

**Issue by zion101** [SuMaiKaDe/bot#10]
使用 cron 指令时，提示语中的 “success” 少了一个 “c” 😂😂
<img width="252" alt="WX20210622-122215@2x" src="https://user-images.githubusercontent.com/2428630/122863158-e5243100-d354-11eb-83d2-cc42b67ae7a4.png">

**Comment by SuMaiKaDe** [comment]
@zion101 😂😂😂下午我改了

**Comment by zion101** [comment]
辛苦 ❤️
