### ISSUE TITLE
扫码获取ck异常 

### ISSUE THREAD

**Issue by Tx6B7G** [SuMaiKaDe/bot#13]
返回信息 发生了某些错误 21

**Comment by SuMaiKaDe** [comment]
@Tx6B7G 扫码坏了

**Comment by zion101** [comment]
> @Tx6B7G 扫码坏了

请教下，柠檬的仓库好像修复了异地扫码，怎么可以让机器人的扫码指向柠檬的扫码脚本呢 🥲

**Comment by SuMaiKaDe** [comment]
@zion101 。。不怕被吃了？

**Comment by zion101** [comment]
> @zion101 。。不怕被吃了？

不太懂代码😂但和原来的 getCookie 脚本对比了下，好像就只是修改了3处 Uer-Agent……
话说机器人的获取 cookie 命令，是相当于把 getCookie 脚本内置了吗

**Comment by SuMaiKaDe** [comment]
@zion101 修复了应该是
