### ISSUE TITLE
QL2.8的myck貌似有问题，还请看下。

### ISSUE THREAD

**Issue by douzicao** [SuMaiKaDe/bot#17]
调用myck后运行日志提示：[qlenv] search-->JD_COOKIE-->eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiakRCbGZLeGNnQS1LbXhiMG5BcFB4WTcjN2xVYk9kRjBOSiNLN3VxcW1NU2Rad0NZemUyTDFqeW0wRk8iLCJpYXQiOjE2MjU1NTM3ODAsImV4cCI6MTYyNTgxMjk4MH0.n1BzJx3folZ90h0mB272ZnjQm19Z79WIAPYySZYJIsn6XHDaYH7ciXGoT0_LqoIx

**Comment by SuMaiKaDe** [comment]
@douzicao 有什么问题

**Comment by douzicao** [comment]
> @douzicao 有什么问题

比如关注店铺不会执行后面的动作。
我的代码是cookies = myck(_ConfigFile)
然后你的bot里面的utils的_ConfigFile路径不是f'{_ConfigDir}/env.sh'而是Auth文件
感觉是这个问题。
我没办法调试，因为青龙重启机器人就会覆盖掉。

**Comment by SuMaiKaDe** [comment]
@douzicao 不明白，代码有什么问题吗是？

**Comment by douzicao** [comment]
> @douzicao 不明白，代码有什么问题吗是？

我感觉是我调用myck的方式有问题，现在myck()怎么调用呢？

**Comment by SuMaiKaDe** [comment]
@douzicao myck(file)根据是青龙还是V4调用file，如果是v4直接读取file里的ck，如果是青龙需要file是auth.json会读取里边的token

**Comment by douzicao** [comment]
> @douzicao myck(file)根据是青龙还是V4调用file，如果是v4直接读取file里的ck，如果是青龙需要file是auth.json会读取里边的token
我明白了，[qlenv] search-->JD_COOKIE--后面跟的就是我的token。是用token登录后去搜JD_COOKIE变量吗？

**Comment by SuMaiKaDe** [comment]
@douzicao 你看的是打印结果，返回值都是用正则匹配到的ck列表

**Comment by douzicao** [comment]
> @douzicao 你看的是打印结果，返回值都是用正则匹配到的ck列表

我明白了，多谢。
