### ISSUE TITLE
报session冲突怎么解决呢

### ISSUE THREAD

**Issue by sofs2005** [SuMaiKaDe/bot#19]
telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest)

说session被两个ip用了，我网上查了下说删掉session文件就可以了，不过我找了好久都没找到在哪里，我用的是v4 bot版

**Comment by SuMaiKaDe** [comment]
应该是在/jd目录下
