### ISSUE TITLE
/set 命令无法正常运行

### ISSUE THREAD

**Issue by duan-1** [SuMaiKaDe/bot#37]
其他的命令都没有问题，就是/set命令会提示，缺少文件。Google了很久，在电报群里也求助了很多次，仓库里也找了很久的文件和说明发现都没有这个文件。希望可以的得到解答
![image](https://user-images.githubusercontent.com/61895588/134792001-3059988d-76ce-4e10-a15e-a430f0bdc487.png)

**Comment by SuMaiKaDe** [comment]
@duan-1 知道了，，但是没电脑，手机改会出现错位，等晚上吧

**Comment by duan-1** [comment]
劳烦大佬了(๑•̀ㅂ•́)و✧

**Comment by duan-1** [comment]
@SuMaiKaDe 劳烦大佬了(๑•̀ㅂ•́)و✧
