### ISSUE TITLE
启动报错The api_id/api_hash combination is invalid

### ISSUE THREAD

**Issue by wzsxlh** [SuMaiKaDe/bot#45]
api_id和api_hash从网站上复制下来的，这个应该是没问题的，但是启动报了这个错。

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 72, in <module>
    jdbot = TelegramClient('bot', API_ID, API_HASH,
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/usr/lib/python3.9/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

如果大佬知道的话，麻烦告知一下解决方案，谢谢。

**Comment by wzsxlh** [comment]
找到问题了，打扰

**Comment by Eternity-luo** [comment]
> 找到问题了，打扰

请问这是哪里错了，我也是这样报错😂

**Comment by wzsxlh** [comment]
> 

这个地方检查一下:
你应该也是用的青龙把，ql bot这个命令会先拉取仓库，把文件都放在repo这个目录下面，然后把配置文件拷贝到/ql/config下，所以你要检查青龙容器里面这个目录下面的bot.json中的api_id和api_hash是否填写正确，而不是去修改/ql/repo/dockerbot下面的bot.json，ql bot他只会在/ql/config下面没有bot.json才复制过来，所以第一次要么你手动拉机器人的这个仓库，要么就是ql bot命令之后自己去修改/ql/config下面的bot.json
我就是这个地方弄错了，一直修改的是拉取下来仓库的配置文件，实际上青龙用的不是这个配置文件，所以启动失败。

**Comment by wzsxlh** [comment]
> > 找到问题了，打扰
> 
> 请问这是哪里错了，我也是这样报错😂

这个地方检查一下:
你应该也是用的青龙把，ql bot这个命令会先拉取仓库，把文件都放在repo这个目录下面，然后把配置文件拷贝到/ql/config下，所以你要检查青龙容器里面这个目录下面的bot.json中的api_id和api_hash是否填写正确，而不是去修改/ql/repo/dockerbot下面的bot.json，ql bot他只会在/ql/config下面没有bot.json才复制过来，所以第一次要么你手动拉机器人的这个仓库，要么就是ql bot命令之后自己去修改/ql/config下面的bot.json
我就是这个地方弄错了，一直修改的是拉取下来仓库的配置文件，实际上青龙用的不是这个配置文件，所以启动失败。

**Comment by zhouy005x** [comment]
> > > 找到问题了，打扰
> > 
> > 
> > 请问这是哪里错了，我也是这样报错joy
> 
> 这个地方检查一下: 你应该也是用的青龙把，ql bot这个命令会先拉取仓库，把文件都放在repo这个目录下面，然后把配置文件拷贝到/ql/config下，所以你要检查青龙容器里面这个目录下面的bot.json中的api_id和api_hash是否填写正确，而不是去修改/ql/repo/dockerbot下面的bot.json，ql bot他只会在/ql/config下面没有bot.json才复制过来，所以第一次要么你手动拉机器人的这个仓库，要么就是ql bot命令之后自己去修改/ql/config下面的bot.json 我就是这个地方弄错了，一直修改的是拉取下来仓库的配置文件，实际上青龙用的不是这个配置文件，所以启动失败。

我只有在ql/config里面进行修改过，api_id和api_hash都核对过，但是还是报错
![-3db2e30cf126581a](https://user-images.githubusercontent.com/64981486/143620722-445bced5-8372-424d-98c1-99b61ffae28b.png)

**Comment by zhouy005x** [comment]
昨天一天的run.log日志大小已经17.1M了😂

**Comment by Eternity-luo** [comment]
> > > 找到问题了，打扰
> > 
> > 
> > 请问这是哪里错了，我也是这样报错joy
> 
> 这个地方检查一下: 你应该也是用的青龙把，ql bot这个命令会先拉取仓库，把文件都放在repo这个目录下面，然后把配置文件拷贝到/ql/config下，所以你要检查青龙容器里面这个目录下面的bot.json中的api_id和api_hash是否填写正确，而不是去修改/ql/repo/dockerbot下面的bot.json，ql bot他只会在/ql/config下面没有bot.json才复制过来，所以第一次要么你手动拉机器人的这个仓库，要么就是ql bot命令之后自己去修改/ql/config下面的bot.json 我就是这个地方弄错了，一直修改的是拉取下来仓库的配置文件，实际上青龙用的不是这个配置文件，所以启动失败。

我只有在ql/config里面进行修改过，api_id和api_hash都核过，但是bot还是报错😂
![Uploading -3db2e30cf126581a.png…]()

**Comment by Eternity-luo** [comment]
> > > 找到问题了，打扰了
> > 
> > 
> > 好像这是哪里错了，我也是这样报错喜悦
> 
> 这个地方检查一下： 你应该也是用的青龙把，ql bot这个命令会先拉取仓库，把文件都repo这个目录下面，然后把配置文件拷贝到/ql/config下，所以你要检查青龙容器里面这个目录下面的bot.json中的api_id和api_hash是否正确，而不是去修改/ql/repo/dockerbot下面的bot.json，ql bot他的兴趣在/ql/config下面没有bot.json复制过来，所以机器人第一次不是你手动拉的， 这个地方之后就是ql bot命令自己去修改/ql/config下面的bot.json我就是弄弄错了，一直修改的是拉取下来仓库的配置文件，实际上青龙用的不是配置文件，所以启动失败。

我只有在ql/config里面进行修改过，api_id和api_hash都核过，但是bot还是报错😂
![-3db2e30cf126581a](https://user-images.githubusercontent.com/72162184/143625678-b8fdf582-a07c-474d-897e-0dd8f449870a.png)

**Comment by Eternity-luo** [comment]
可以加个tg吗

**Comment by Eternity-luo** [comment]
@L_Morgen

**Comment by wzsxlh** [comment]
你这个报错重启一下应该就可以了，再试试

**Comment by Eternity-luo** [comment]
> 你这个帖子重启一下就可以了，再恢复一下

感谢，解决了，是代理的问题

**Comment by 8917007** [comment]
我也遇到这个错误，不过我不是在青龙里使用，我是想弄Tg名字显示时间，运行python3 tg_username_update.py 出现这个问题，怎么解决？
