### ISSUE TITLE
/snode失败

### ISSUE THREAD

**Issue by KID-Nick** [SuMaiKaDe/bot#5]
### 青龙   机器人使用 /snode 失败
> something wrong,I'm sorry
The data embedded in the reply markup buttons was too much (caused by EditMessageRequest)
![1](https://user-images.githubusercontent.com/67312004/121795364-91be2e80-cc42-11eb-80c7-201f8d8c17c3.jpg)
![2](https://user-images.githubusercontent.com/67312004/121795367-94208880-cc42-11eb-84ae-bb122e30aa29.jpg)
请作者帮忙康康，感谢

**Comment by SuMaiKaDe** [comment]
中文那里改成True或者更新bot
