### ISSUE TITLE
进行bash bot.sh时显示No such file or directory

### ISSUE THREAD

**Issue by l8higher** [SuMaiKaDe/bot#6]
![image](https://user-images.githubusercontent.com/57839836/121826159-efa55180-cce8-11eb-8bd0-9e90b4eceec9.png)
已将bot.sh放入ql文件夹的comfig内，如图操作，希望大佬指点一下。

**Comment by liyiecho** [comment]
进入config文件夹后再`bash bot.sh`，或者在当前目录下`bash config/bot.sh`

**Comment by l8higher** [comment]
> 进入config文件夹后再`bash bot.sh`，或者在当前目录下`bash config/bot.sh`

谢谢老哥 解决了！
