### ISSUE TITLE
问候语开启之后，在青龙里面输入pm2 restart jbot，机器人并没有发送问候语

### ISSUE THREAD

**Issue by VectorZhao** [SuMaiKaDe/bot#7]

**Comment by VectorZhao** [comment]
{
  "版本": "0.0.7",
  "每页列数": 3,
  "中文": "True",
  "开启机器人转发": "False",
  "机器人黑名单": "",
  "机器人垃圾话": "",
  "下载代理": "https://ghproxy.com",
  "启动问候": "True",
  "启动问候语": "叮咚，我已成功启动，欢迎使用",
  "开启别名": "False",
  "命令别名": {
    "bean": "表格",
    "chart": "豆子",
    "cmd": "命令",
    "cron": "任务",
    "set": "设置",
    "edit": "编辑",
    "setname": "别名",
    "reply": "回复",
    "getcookie": "扫码",
    "dl": "下载",
    "node": "运行脚本",
    "snode": "执行",
    "getfile": "文件",
    "log": "日志",
    "setshort": "快捷设定",
    "a": "快捷",
    "b": "键盘"
  }
}

**Comment by SuMaiKaDe** [comment]
你这是设置的哪个json？

**Comment by VectorZhao** [comment]
ql/config/botset.json
这个文件

**Comment by SuMaiKaDe** [comment]
@VectorZhao 😂青龙不是pm2直接ql bot命令重启

**Comment by VectorZhao** [comment]
@SuMaiKaDe   原来得ql bot 才好使啊，我还以为pm2 restart jbot就可以呢😂

**Comment by VectorZhao** [comment]
@SuMaiKaDe 感谢感谢，有启动欢迎语了
