### ISSUE TITLE
fake产品经理提需求～

### ISSUE THREAD

**Issue by ZCY01** [SuMaiKaDe/bot#9]
建议在tg扫码获取cookies的时候，添加是否替换config.sh里面cookie的选项
由于pt_pin是固定的，可以根据pt_pin定位到对应的旧cookie.
感谢🙏！

**Comment by SuMaiKaDe** [comment]
@ZCY01 不可能加的。

**Comment by SuMaiKaDe** [comment]
@ZCY01 会变成很多人的代挂工具

**Comment by ZCY01** [comment]
了解🙈
